// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebHoTroHocLapTrinh.Data;

namespace WebHoTroHocLapTrinh.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220607101647_AddTblSubjectChapter")]
    partial class AddTblSubjectChapter
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebHoTroHocLapTrinh.Data.Chapter", b =>
                {
                    b.Property<Guid>("IdChapter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdSubject")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameChapter")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdChapter");

                    b.HasIndex("IdSubject");

                    b.ToTable("Chapter");
                });

            modelBuilder.Entity("WebHoTroHocLapTrinh.Data.Exercise", b =>
                {
                    b.Property<Guid>("IdExercise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diffculty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdChapter")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameExercise")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdExercise");

                    b.HasIndex("IdChapter");

                    b.ToTable("Exercise");
                });

            modelBuilder.Entity("WebHoTroHocLapTrinh.Data.Subject", b =>
                {
                    b.Property<Guid>("IdSubject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameSubject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdSubject");

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("WebHoTroHocLapTrinh.Data.Chapter", b =>
                {
                    b.HasOne("WebHoTroHocLapTrinh.Data.Subject", "Subject")
                        .WithMany("Chapters")
                        .HasForeignKey("IdSubject");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("WebHoTroHocLapTrinh.Data.Exercise", b =>
                {
                    b.HasOne("WebHoTroHocLapTrinh.Data.Chapter", "Chapter")
                        .WithMany("Exercises")
                        .HasForeignKey("IdChapter");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("WebHoTroHocLapTrinh.Data.Chapter", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("WebHoTroHocLapTrinh.Data.Subject", b =>
                {
                    b.Navigation("Chapters");
                });
#pragma warning restore 612, 618
        }
    }
}
